/**
 * Integrity tests for the shipped data pack.
 *
 * The pack is generated by pipeline/build_pack.py and is the single input the whole app
 * trusts. A silent regression here -- a NaN, a dropped bye, a team whose targets stop
 * adding up -- would not throw anywhere; it would just quietly make every projection and
 * every trade verdict wrong. So the pack gets asserted like code.
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { scoreLine, DEFAULT_SCORING, PRESETS, expectedDstScore } from '../app/js/scoring.js'

globalThis.window = globalThis.window || {}
await import('../app/data/pack.js')
const pack = globalThis.window.TD_PACK

const POS = ['QB', 'RB', 'WR', 'TE', 'K', 'DST']
const offense = pack.players.filter((p) => ['QB', 'RB', 'WR', 'TE'].includes(p.pos) && p.mu)

test('pack loads with the expected top-level shape', () => {
  for (const k of ['meta', 'logKeys', 'teams', 'schedule', 'teamFactors', 'teamBase',
    'dvp', 'sos', 'coef', 'players', 'playoffWeeks']) {
    assert.ok(pack[k] !== undefined, `missing top-level key: ${k}`)
  }
  assert.equal(Object.keys(pack.teams).length, 32)
  assert.ok(pack.players.length > 900, `only ${pack.players.length} players`)
  assert.equal(pack.meta.season, 2026)
})

test('every player has the fields the app requires', () => {
  for (const p of pack.players) {
    assert.ok(p.id && typeof p.id === 'string', `bad id: ${JSON.stringify(p).slice(0, 80)}`)
    assert.ok(p.name && typeof p.name === 'string', `bad name for ${p.id}`)
    assert.ok(POS.includes(p.pos), `bad pos ${p.pos} for ${p.name}`)
    assert.ok(typeof p.team === 'string' && p.team.length <= 3, `bad team for ${p.name}`)
    assert.ok(p.avail > 0 && p.avail <= 1, `avail out of range for ${p.name}: ${p.avail}`)
    assert.ok(Number.isInteger(p.bye) && p.bye >= 0 && p.bye <= 18, `bad bye for ${p.name}`)
  }
})

test('no NaN, Infinity or negative volume anywhere in the projections', () => {
  const bad = []
  for (const p of pack.players) {
    const groups = [p.mu, ...Object.values(p.kWeeks || {}), ...Object.values(p.dstWeeks || {})]
    for (const g of groups) {
      if (!g) continue
      for (const [k, v] of Object.entries(g)) {
        if (!Number.isFinite(v)) bad.push(`${p.name}.${k}=${v}`)
        // Points allowed is the only component where a negative would be meaningless
        // rather than merely odd; everything else is a count or a yardage.
        if (v < 0 && !['fuml', 'pint'].includes(k)) bad.push(`${p.name}.${k}=${v} negative`)
      }
    }
  }
  assert.deepEqual(bad.slice(0, 10), [], `${bad.length} bad values`)
})

test('scoring the pack never produces NaN under any preset', () => {
  for (const [name, cfg] of Object.entries(PRESETS)) {
    for (const p of pack.players) {
      const line = p.mu || Object.values(p.kWeeks || {})[0] || Object.values(p.dstWeeks || {})[0]
      if (!line) continue
      const s = scoreLine(line, cfg, p.pos)
      assert.ok(Number.isFinite(s), `${name} scored ${p.name} as ${s}`)
    }
  }
})

test('team usage reconciles to a real football game once availability-weighted', () => {
  // Shares are conditional on playing, so the constraint is SUM(active * share) = 1.
  // Raw sums legitimately run ~1.4x; see model.reconcile_to_team.
  const byTeam = {}
  for (const p of offense) {
    const t = (byTeam[p.team] ||= { tgt: 0, ratt: 0, reyd: 0, td: 0 })
    const a = p.act ?? 0.5
    t.tgt += a * (p.mu.tgt || 0)
    t.ratt += a * (p.mu.ratt || 0)
    t.reyd += a * (p.mu.reyd || 0)
    t.td += a * ((p.mu.rtd || 0) + (p.mu.retd || 0))
  }
  const teams = Object.entries(byTeam)
  assert.ok(teams.length >= 32, `only ${teams.length} teams have projected offenses`)
  const mean = (k) => teams.reduce((s, [, v]) => s + v[k], 0) / teams.length

  // Real NFL per-game values, with room for genuine team variation.
  assert.ok(mean('tgt') > 29 && mean('tgt') < 36, `targets/game ${mean('tgt')}`)
  assert.ok(mean('ratt') > 23 && mean('ratt') < 31, `carries/game ${mean('ratt')}`)
  assert.ok(mean('reyd') > 200 && mean('reyd') < 280, `rec yards/game ${mean('reyd')}`)
  assert.ok(mean('td') > 2.0 && mean('td') < 3.1, `off TDs/game ${mean('td')}`)

  for (const [team, v] of teams) {
    assert.ok(v.tgt > 25 && v.tgt < 40, `${team} targets/game ${v.tgt}`)
    assert.ok(v.ratt > 20 && v.ratt < 34, `${team} carries/game ${v.ratt}`)
  }
})

test('receiving yards equal passing yards - they are the same yards', () => {
  const rec = {}
  for (const p of offense) rec[p.team] = (rec[p.team] || 0) + (p.act ?? 0.5) * (p.mu.reyd || 0)
  let totRec = 0, totPass = 0
  for (const [team, v] of Object.entries(rec)) {
    totRec += v
    totPass += pack.teamBase[team]?.pass_yds || 0
  }
  const ratio = totRec / totPass
  assert.ok(Math.abs(ratio - 1) < 0.03, `receiving/passing yard ratio is ${ratio.toFixed(3)}`)
})

test('every team has a bye and a full schedule', () => {
  for (const [team, weeks] of Object.entries(pack.schedule)) {
    assert.ok(weeks.length >= 16 && weeks.length <= 18, `${team} has ${weeks.length} games`)
    const seen = new Set(weeks.map((w) => w.w))
    assert.equal(seen.size, weeks.length, `${team} has a duplicate week`)
    const bye = pack.teams[team].bye
    assert.ok(bye >= 4 && bye <= 14, `${team} bye ${bye} is implausible`)
    assert.ok(!seen.has(bye), `${team} plays in its own bye week ${bye}`)
    for (const w of weeks) {
      assert.ok(w.implied > 10 && w.implied < 40, `${team} wk${w.w} implied ${w.implied}`)
      assert.ok(['market', 'model'].includes(w.src), `${team} wk${w.w} bad src`)
      assert.ok(pack.teams[w.opp], `${team} wk${w.w} unknown opponent ${w.opp}`)
    }
  }
})

test('a player never shares a bye with a different team', () => {
  for (const p of pack.players) {
    if (!pack.teams[p.team]) continue
    assert.equal(p.bye, pack.teams[p.team].bye, `${p.name} (${p.team}) bye mismatch`)
  }
})

test('indoor teams are recorded as indoor - the kicker adjustment depends on it', () => {
  // These five had null roof in the source feed and are filled from the prior season.
  for (const team of ['ARI', 'ATL', 'DAL', 'HOU', 'IND', 'DET', 'MIN', 'NO', 'LV']) {
    const home = pack.schedule[team].filter((w) => w.home)
    const indoor = home.filter((w) => ['dome', 'closed'].includes(String(w.roof).toLowerCase()))
    assert.equal(indoor.length, home.length,
      `${team} has ${home.length - indoor.length} home games recorded as outdoors`)
  }
  // And an outdoor team stays outdoors, so the fallback did not overreach.
  const gb = pack.schedule.GB.filter((w) => w.home)
  assert.ok(gb.every((w) => w.roof === 'outdoors'), 'GB should be outdoors at home')
})

test('defense-vs-position multipliers are shrunk, not wild', () => {
  for (const [team, byPos] of Object.entries(pack.dvp)) {
    for (const [pos, mult] of Object.entries(byPos)) {
      assert.ok(mult > 0.85 && mult < 1.15, `dvp ${team}/${pos} = ${mult} is outside the clamp`)
    }
  }
})

test('strength of schedule covers every team and both windows', () => {
  for (const team of Object.keys(pack.teams)) {
    const s = pack.sos[team]
    assert.ok(s, `no SoS for ${team}`)
    for (const pos of ['QB', 'RB', 'WR', 'TE']) {
      assert.ok(s[pos].season > 0.85 && s[pos].season < 1.15, `${team} ${pos} season SoS ${s[pos].season}`)
      assert.ok(s[pos].playoff > 0.8 && s[pos].playoff < 1.2, `${team} ${pos} playoff SoS ${s[pos].playoff}`)
    }
    assert.ok(s.oppOffense.playoff > 14 && s.oppOffense.playoff < 32)
  }
})

test('historical logs unpack and rescore correctly', () => {
  const K = pack.logKeys
  const withLog = pack.players.filter((p) => p.log?.length)
  assert.ok(withLog.length > 500, `only ${withLog.length} players have logs`)

  for (const p of withLog.slice(0, 200)) {
    for (const row of p.log) {
      assert.equal(row.length, K.length + 3, `${p.name} log row wrong width`)
      assert.ok(pack.meta.logSeasons.includes(row[0]), `${p.name} log season ${row[0]}`)
      assert.ok(row[1] >= 1 && row[1] <= 22, `${p.name} log week ${row[1]}`)
    }
  }

  // Full PPR minus half PPR must equal exactly half the receptions. This is the tightest
  // available check that the log, the key order, and the scoring engine all agree.
  const chase = pack.players.find((p) => p.name === "Ja'Marr Chase")
  const rows = chase.log.map((r) => {
    const o = {}
    for (let i = 0; i < K.length; i++) o[K[i]] = r[i + 3]
    return o
  })
  const full = rows.reduce((s, l) => s + scoreLine(l, PRESETS.fullPPR, 'WR'), 0)
  const half = rows.reduce((s, l) => s + scoreLine(l, PRESETS.halfPPR, 'WR'), 0)
  const recs = rows.reduce((s, l) => s + l.rec, 0)
  assert.ok(Math.abs((full - half) - recs / 2) < 0.01,
    `full-half=${full - half} but receptions/2=${recs / 2}`)
})

test('D/ST carries a full weekly slate and a usable dispersion', () => {
  const dsts = pack.players.filter((p) => p.pos === 'DST')
  assert.equal(dsts.length, 32)
  for (const d of dsts) {
    const weeks = Object.keys(d.dstWeeks || {})
    assert.ok(weeks.length >= 16, `${d.team} D/ST has ${weeks.length} weeks`)
    assert.ok(d.dstSd.ptsAllowed > 4 && d.dstSd.ptsAllowed < 15, `${d.team} PA sd`)
    assert.ok(d.dstSd.ydsAllowed > 40 && d.dstSd.ydsAllowed < 130, `${d.team} YA sd`)
    for (const mu of Object.values(d.dstWeeks)) {
      assert.ok(mu.ptsAllowed > 8 && mu.ptsAllowed < 40, `${d.team} PA ${mu.ptsAllowed}`)
      assert.ok(Number.isFinite(expectedDstScore(mu, DEFAULT_SCORING, d.dstSd)))
    }
  }
})

test('kickers carry a weekly slate with sane field-goal volume', () => {
  const ks = pack.players.filter((p) => p.pos === 'K' && p.kWeeks)
  assert.ok(ks.length >= 30, `only ${ks.length} kickers with weekly projections`)
  for (const k of ks) {
    for (const mu of Object.values(k.kWeeks)) {
      const att = Object.keys(mu).filter((x) => x.startsWith('fgm_') || x.startsWith('fgx_'))
        .reduce((s, x) => s + mu[x], 0)
      assert.ok(att > 0.5 && att < 5, `${k.name} projected ${att} FG attempts`)
      assert.ok(mu.xpm >= 0 && mu.xpm < 6, `${k.name} xpm ${mu.xpm}`)
    }
  }
})

test('the market blend moved players but never rewrote them', () => {
  const moved = pack.players.filter((p) => p.blendAdj)
  assert.ok(moved.length > 300, `only ${moved.length} players blended`)
  for (const p of moved) {
    assert.ok(p.blendAdj >= 0.55 && p.blendAdj <= 1.8,
      `${p.name} blendAdj ${p.blendAdj} escaped the clamp`)
  }
})

test('provenance is recorded so the app can show data age', () => {
  assert.ok(pack.meta.generated, 'no generated timestamp')
  assert.ok(Array.isArray(pack.meta.sources) && pack.meta.sources.length > 20)
  for (const s of pack.meta.sources) {
    assert.ok(s.url && s.sha256 && s.bytes > 0, `incomplete source record: ${s.key}`)
  }
  const cov = pack.meta.marketCoverage
  assert.ok(cov.market_share > 0 && cov.market_share < 1)
  assert.ok(pack.meta.integrity.spread_orientation.orientation === 'home_positive_when_favored')
  assert.equal(pack.meta.integrity.bye_weeks.disagree, 0, 'schedule byes disagree with published byes')
  assert.ok(pack.meta.integrity.td_regression.expected_beats_realized,
    'expected TDs should beat realized TDs at predicting the next season')
})
