/**
 * Tests for app/js/projections.js — the pack turned into projections.
 *
 * Run: cd /home/user/tradedesk && npm test
 *
 * These run against the REAL data pack, not fixtures, because the things worth testing here
 * are relationships between the pack's own numbers. Nothing asserts a hard-coded projection:
 * the pack is regenerated by the pipeline, so every assertion is either structural, an exact
 * algebraic identity re-derived from the pack in the test, or a synthetic fixture with a
 * hand-computed answer.
 *
 * The six claims that have to hold:
 *   1. A bye is a bye. weeklyMu returns null, and no projection quietly counts the week.
 *   2. Composition is exactly mu x team-week channel factor x opponent DvP, with pass
 *      components on `pass`, rush on `rush` and touchdowns on `td`.
 *   3. Full PPR is the point of the app: halving `rec.rec` must move WRs a lot and QBs almost
 *      not at all — and the size of the WR move must equal 0.5 x projected receptions exactly.
 *   4. A dome kicker is not the same as an outdoor one.
 *   5. historicalPPG is real history: it reproduces arithmetic done by hand off the log rows.
 *   6. projectFast re-derives the whole 1000-player board fast enough to keep the UI live
 *      while the user drags a scoring slider.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  loadPack,
  weeklyMu,
  project,
  projectFast,
  weeklyProjection,
  restOfSeason,
  seasonTotal,
  historicalPPG,
  unpackLog,
  quantileOf,
  useSim,
  simEngine,
  COMPONENT_CHANNEL,
  EVENT_COMPONENTS,
} from '../app/js/projections.js';

import { PRESETS, scoreLine, cloneScoring } from '../app/js/scoring.js';

/* ------------------------------------------------------------------ the pack */

// pack.js is a plain script that assigns `window.TD_PACK`. Evaluating it against a local
// object keeps the test free of any module-system assumption and leaves no global behind.
const PACK = (() => {
  const src = readFileSync(new URL('../app/data/pack.js', import.meta.url), 'utf8');
  const win = {};
  // eslint-disable-next-line no-new-func
  new Function('window', src)(win);
  return win.TD_PACK;
})();

const VIEW = loadPack(PACK);
const FULL = PRESETS.fullPPR;
const HALF = PRESETS.halfPPR;

const EPS = 1e-9;

function close(a, b, tol) {
  return Math.abs(a - b) <= (tol === undefined ? 1e-6 : tol);
}

/** Players at a position, sorted by full-PPR season projection, best first. */
function topAt(pos, n) {
  const list = (VIEW.byPos.get(pos) || []).map((p) => ({
    player: p,
    proj: projectFast(p, { pack: VIEW, cfg: FULL, perWeek: false }),
  }));
  list.sort((a, b) => b.proj.mean - a.proj.mean);
  return list.slice(0, n);
}

function scheduledWeeks(team) {
  const list = PACK.schedule[team];
  return Array.isArray(list) ? list.map((g) => g.w) : [];
}

/* ------------------------------------------------------------ 0. pack sanity */

test('the pack under test has the shape these tests assume', () => {
  assert.ok(Array.isArray(PACK.players) && PACK.players.length > 500,
    'expected a real pack with hundreds of players');
  assert.ok(Array.isArray(PACK.logKeys) && PACK.logKeys.length > 0);
  for (const key of ['schedule', 'teamFactors', 'dvp', 'teams', 'meta']) {
    assert.equal(typeof PACK[key], 'object', `pack.${key} must be an object`);
  }
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K', 'DST']) {
    assert.ok((VIEW.byPos.get(pos) || []).length > 0, `pack has no ${pos}`);
  }
});

/* ------------------------------------------------------------------ loadPack */

test('loadPack indexes the pack without copying or mutating it', () => {
  const view = loadPack(PACK);

  assert.equal(view.players.length, PACK.players.length);
  assert.notEqual(view.players, PACK.players, 'players array must be a fresh array');
  assert.equal(view.players[0], PACK.players[0], 'but it must hold the same player objects');
  assert.equal(view.schedule, PACK.schedule);
  assert.equal(view.teams, PACK.teams);
  assert.equal(view.meta, PACK.meta);

  assert.ok(view.byId instanceof Map);
  assert.ok(view.byPos instanceof Map);
  assert.ok(view.byTeam instanceof Map);

  // Every player is reachable by id, position and team.
  let missing = 0;
  for (const p of PACK.players) {
    if (view.byId.get(String(p.id)) !== p) missing++;
    if (!(view.byPos.get(p.pos) || []).includes(p)) missing++;
    if (!(view.byTeam.get(p.team) || []).includes(p)) missing++;
  }
  assert.equal(missing, 0);

  // Weeks span the whole regular season.
  assert.equal(view.weeks[0], 1);
  assert.equal(view.weeks[view.weeks.length - 1], view.lastWeek);
  assert.ok(view.lastWeek >= 17);
});

test('loadPack is idempotent and caches per pack object', () => {
  assert.equal(loadPack(PACK), loadPack(PACK), 'same pack must yield the same view');
  assert.equal(loadPack(VIEW), VIEW, 'a view passed back in is returned unchanged');
});

test('loadPack survives garbage input', () => {
  for (const bad of [null, undefined, 0, 'x', [], true]) {
    const v = loadPack(bad);
    assert.equal(v.players.length, 0);
    assert.equal(v.gameFor('KC', 1), null);
    assert.ok(Array.isArray(v.weeks) && v.weeks.length > 0);
  }
});

test('gameFor and byeOf agree with the schedule', () => {
  for (const team of Object.keys(PACK.schedule)) {
    const bye = VIEW.byeOf(team);
    assert.ok(bye > 0, `${team} has no bye week in pack.teams`);
    assert.equal(VIEW.gameFor(team, bye), null,
      `${team} must have no scheduled game in its bye week ${bye}`);
    for (const g of PACK.schedule[team]) {
      assert.equal(VIEW.gameFor(team, g.w), g);
      assert.notEqual(g.w, bye, `${team} is scheduled in its own bye week`);
    }
  }
});

/* ------------------------------------------------------ 1. byes are structural */

test('weeklyMu returns null on every bye week, for every player', () => {
  let checked = 0;
  for (const p of PACK.players) {
    const bye = p.bye;
    if (!(bye > 0)) continue;
    if (!PACK.schedule[p.team]) continue;
    assert.equal(weeklyMu(p, bye, PACK), null,
      `${p.name} (${p.team}) returned a stat line for his bye week ${bye}`);
    checked++;
  }
  assert.ok(checked > 500, 'expected to check hundreds of players');
});

test('weeklyMu returns a line for every week the team actually plays', () => {
  const sample = [];
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K', 'DST']) {
    sample.push(...(VIEW.byPos.get(pos) || []).slice(0, 25));
  }
  let lines = 0;
  for (const p of sample) {
    const hasData = p.mu || p.kWeeks || p.dstWeeks;
    if (!hasData || !PACK.schedule[p.team]) continue;
    for (const w of scheduledWeeks(p.team)) {
      const mu = weeklyMu(p, w, PACK);
      assert.ok(mu !== null, `${p.name} has no line for scheduled week ${w}`);
      lines++;
    }
  }
  assert.ok(lines > 1000);
});

test('weeklyMu rejects weeks outside the schedule and unknown teams', () => {
  const wr = topAt('WR', 1)[0].player;
  for (const bad of [0, -1, 19, 99, NaN, null, undefined, 'x']) {
    assert.equal(weeklyMu(wr, bad, PACK), null, `week ${String(bad)} should be null`);
  }
  const orphan = { id: 'x', name: 'Nobody', pos: 'WR', team: 'ZZZ', bye: 0, mu: { rec: 5 }, cv: 0.4, avail: 1 };
  assert.equal(weeklyMu(orphan, 1, PACK), null);
  assert.equal(weeklyMu(null, 1, PACK), null);
});

test('a bye is not scored, and games + byes account for every requested week', () => {
  const wr = topAt('WR', 1)[0].player;
  const s = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  assert.equal(s.games + s.byes.length, s.weeks.length);
  assert.ok(s.byes.includes(wr.bye), 'the player bye week must be reported as a bye');
  const byeRow = s.perWeek.find((r) => r.week === wr.bye);
  assert.equal(byeRow.bye, true);
  assert.equal(byeRow.mean, 0);
  assert.equal(byeRow.sd, 0);
  assert.equal(byeRow.p90, 0);

  // Projecting only the bye week yields nothing at all, and says so.
  const only = projectFast(wr, { pack: VIEW, weeks: [wr.bye] });
  assert.equal(only.games, 0);
  assert.equal(only.mean, 0);
  assert.ok(only.note.length > 0);
});

/* ------------------------------------------- 2. composition: factors and DvP */

test('weeklyMu composes mu x team-week channel factor x opponent DvP, component by component', () => {
  let players = 0;
  for (const pos of ['QB', 'RB', 'WR', 'TE']) {
    for (const { player: p } of topAt(pos, 6)) {
      if (!p.mu || !PACK.schedule[p.team]) continue;
      players++;
      for (const g of PACK.schedule[p.team]) {
        const f = PACK.teamFactors[p.team][String(g.w)];
        const d = PACK.dvp[g.opp][p.pos];
        const mu = weeklyMu(p, g.w, PACK);

        // The blend used by fumbles: the player's own pass-vs-rush opportunity mix.
        const passOpp = (p.mu.patt || 0) + (p.mu.tgt || 0);
        const rushOpp = p.mu.ratt || 0;
        const wPass = (passOpp + rushOpp) > 0 ? passOpp / (passOpp + rushOpp) : 0.5;
        const fVol = wPass * f.pass + (1 - wPass) * f.rush;

        for (const k of Object.keys(p.mu)) {
          const ch = COMPONENT_CHANNEL[k];
          const factor = ch === 'pass' ? f.pass
            : ch === 'rush' ? f.rush
              : ch === 'td' ? f.td
                : ch === 'vol' ? fVol
                  : 1;
          const want = p.mu[k] * factor * d;
          assert.ok(close(mu[k], want, Math.abs(want) * 1e-12 + 1e-12),
            `${p.name} week ${g.w} component ${k}: got ${mu[k]}, expected ${want}`);
        }
      }
    }
  }
  assert.ok(players >= 20);
});

test('the channel map covers the whole offensive vocabulary and routes it sanely', () => {
  for (const k of PACK.logKeys) {
    assert.ok(Object.prototype.hasOwnProperty.call(COMPONENT_CHANNEL, k),
      `component ${k} has no channel assignment`);
  }
  // Receiving rides pass volume; that is the modeling claim, so pin it.
  for (const k of ['tgt', 'rec', 'reyd', 'refd', 're40']) assert.equal(COMPONENT_CHANNEL[k], 'pass');
  for (const k of ['patt', 'pcmp', 'pyd', 'pint', 'psack', 'pfd', 'p40']) {
    assert.equal(COMPONENT_CHANNEL[k], 'pass');
  }
  for (const k of ['ratt', 'ryd', 'rfd', 'r40']) assert.equal(COMPONENT_CHANNEL[k], 'rush');
  for (const k of ['ptd', 'rtd', 'retd']) assert.equal(COMPONENT_CHANNEL[k], 'td');
  assert.ok(EVENT_COMPONENTS.includes('retd') && EVENT_COMPONENTS.includes('rtd'));
});

test('a different opponent moves the line, in the direction DvP says', () => {
  const wr = topAt('WR', 1)[0].player;
  const rows = PACK.schedule[wr.team].map((g) => ({
    w: g.w,
    dvp: PACK.dvp[g.opp].WR,
    factor: PACK.teamFactors[wr.team][String(g.w)].pass,
    reyd: weeklyMu(wr, g.w, PACK).reyd,
  }));
  // Holding the team factor fixed, receiving yards scale with the opponent multiplier.
  for (const a of rows) {
    for (const b of rows) {
      if (!close(a.factor, b.factor, 1e-12)) continue;
      if (a.dvp > b.dvp + 1e-9) {
        assert.ok(a.reyd > b.reyd,
          `week ${a.w} (DvP ${a.dvp}) should out-project week ${b.w} (DvP ${b.dvp})`);
      }
    }
  }
  // And the multipliers are not all 1, or this test proves nothing.
  const spread = Math.max(...rows.map((r) => r.dvp)) - Math.min(...rows.map((r) => r.dvp));
  assert.ok(spread > 0.01, 'DvP should actually vary across a schedule');
});

test('weeklyMu never aliases or mutates the pack', () => {
  const k = (VIEW.byPos.get('K') || []).find((p) => p.kWeeks);
  const d = (VIEW.byPos.get('DST') || [])[0];
  const wr = topAt('WR', 1)[0].player;

  for (const p of [k, d, wr]) {
    const w = scheduledWeeks(p.team)[0];
    const a = weeklyMu(p, w, PACK);
    const b = weeklyMu(p, w, PACK);
    assert.notEqual(a, b, 'each call must return a fresh object');
    assert.deepEqual(a, b, 'and the same values');
  }

  // The K/DST lines are copies of the pack's, not the pack's own objects.
  const kw = k.kWeeks[String(scheduledWeeks(k.team)[0])];
  const got = weeklyMu(k, scheduledWeeks(k.team)[0], PACK);
  assert.notEqual(got, kw);
  for (const key of Object.keys(kw)) assert.equal(got[key], kw[key]);
  got.xpm = 999;
  assert.notEqual(kw.xpm, 999, 'mutating the result must not reach into the pack');
});

test('K and DST read their per-week line straight out of the pack', () => {
  const k = (VIEW.byPos.get('K') || []).find((p) => p.kWeeks);
  for (const w of scheduledWeeks(k.team)) {
    assert.deepEqual(weeklyMu(k, w, PACK), k.kWeeks[String(w)]);
  }
  const d = (VIEW.byPos.get('DST') || [])[0];
  for (const w of scheduledWeeks(d.team)) {
    assert.deepEqual(weeklyMu(d, w, PACK), d.dstWeeks[String(w)]);
  }
});

/* ------------------------------------------------- 3. the full-PPR difference */

test('halving the reception value costs WRs a lot and QBs almost nothing', () => {
  function relDrop(pos, n) {
    const out = [];
    for (const { player, proj } of topAt(pos, n)) {
      const half = projectFast(player, { pack: VIEW, cfg: HALF, perWeek: false });
      assert.ok(proj.mean > 0, `${player.name} should project above zero under full PPR`);
      out.push({ player, full: proj.mean, half: half.mean, rel: (proj.mean - half.mean) / proj.mean });
    }
    return out;
  }

  const wrs = relDrop('WR', 24);
  for (const r of wrs) {
    assert.ok(r.half < r.full,
      `${r.player.name}: half PPR (${r.half}) must be below full PPR (${r.full})`);
    assert.ok(r.rel > 0.08,
      `${r.player.name}: a top WR should lose well over 8% of his value, lost ${(r.rel * 100).toFixed(1)}%`);
  }

  const qbs = relDrop('QB', 24);
  for (const r of qbs) {
    assert.ok(r.rel < 0.01,
      `${r.player.name}: a QB should barely move, moved ${(r.rel * 100).toFixed(2)}%`);
  }

  const meanWr = wrs.reduce((s, r) => s + r.rel, 0) / wrs.length;
  const meanQb = qbs.reduce((s, r) => s + r.rel, 0) / qbs.length;
  assert.ok(meanWr > 20 * meanQb,
    `the WR/QB sensitivity gap is the whole point: WR ${meanWr}, QB ${meanQb}`);
});

test('the size of the PPR swing is exactly 0.5 x projected receptions', () => {
  // An exact algebraic identity, so it pins the composition and the availability weighting
  // at the same time: mean = SUM_w avail * scoreLine(line_w), and the only config change is
  // 0.5 per reception.
  for (const pos of ['WR', 'RB', 'TE', 'QB']) {
    for (const { player, proj } of topAt(pos, 5)) {
      const half = projectFast(player, { pack: VIEW, cfg: HALF, perWeek: false });
      let recs = 0;
      for (const w of scheduledWeeks(player.team)) {
        const mu = weeklyMu(player, w, PACK);
        if (mu) recs += mu.rec || 0;
      }
      const expected = 0.5 * recs * player.avail;
      assert.ok(close(proj.mean - half.mean, expected, 1e-4),
        `${player.name}: PPR swing ${proj.mean - half.mean} != 0.5 x ${recs} x ${player.avail} = ${expected}`);
    }
  }
});

test('kickers and defenses are untouched by the reception setting', () => {
  for (const pos of ['K', 'DST']) {
    for (const { player, proj } of topAt(pos, 8)) {
      const half = projectFast(player, { pack: VIEW, cfg: HALF, perWeek: false });
      assert.equal(half.mean, proj.mean, `${player.name} moved with a receiving rule`);
      assert.equal(half.sd, proj.sd);
    }
  }
});

/* -------------------------------------------------------- 4. dome vs outdoors */

test('a dome kicker is not the same as an outdoor one', () => {
  const FG = { '0_19': 3, '20_29': 3, '30_39': 3, '40_49': 4, '50_59': 5, '60': 6 };
  const buckets = Object.keys(FG);

  /** Field-goal points per field-goal attempt, isolating the roof from game volume. */
  function fgRate(mu) {
    let att = 0;
    let pts = 0;
    for (const b of buckets) {
      const made = mu['fgm_' + b] || 0;
      const missed = mu['fgx_' + b] || 0;
      att += made + missed;
      pts += made * FG[b] - missed; // -1 per miss, the user's league
    }
    return att > 0 ? pts / att : null;
  }

  let both = 0;
  let domeGames = 0;
  let poolDome = 0;
  let poolDomeN = 0;
  let poolOut = 0;
  let poolOutN = 0;

  for (const k of VIEW.byPos.get('K') || []) {
    if (!k.kWeeks || !PACK.schedule[k.team]) continue;
    const dome = [];
    const outdoor = [];
    for (const g of PACK.schedule[k.team]) {
      const mu = weeklyMu(k, g.w, PACK);
      if (!mu) continue;
      const r = fgRate(mu);
      if (r === null) continue;
      if (g.roof === 'dome') { dome.push(r); domeGames++; poolDome += r; poolDomeN++; }
      else if (g.roof === 'outdoors') { outdoor.push(r); poolOut += r; poolOutN++; }
    }
    if (dome.length === 0 || outdoor.length === 0) continue;
    both++;
    const avg = (a) => a.reduce((x, y) => x + y, 0) / a.length;
    assert.ok(avg(dome) > avg(outdoor),
      `${k.name} (${k.team}): dome ${avg(dome)} should beat outdoors ${avg(outdoor)}`);
  }

  assert.ok(domeGames > 20, 'the schedule should contain plenty of dome games');
  assert.ok(both >= 10, `expected many kickers with both roof types, got ${both}`);
  assert.ok(poolDome / poolDomeN > poolOut / poolOutN,
    'league-wide, kicking in a dome must be worth more per attempt');
});

test('the roof shows up in the projection, not just the raw line', () => {
  const k = (VIEW.byPos.get('K') || []).find((p) => {
    if (!p.kWeeks || !PACK.schedule[p.team]) return false;
    const roofs = new Set(PACK.schedule[p.team].map((g) => g.roof));
    return roofs.has('dome') && roofs.has('outdoors');
  });
  assert.ok(k, 'expected at least one kicker playing both indoors and outdoors');

  const proj = seasonTotal(k, { pack: VIEW, cfg: FULL });
  const rows = new Map(proj.perWeek.map((r) => [r.week, r]));
  const dome = PACK.schedule[k.team].filter((g) => g.roof === 'dome').map((g) => rows.get(g.w));
  const out = PACK.schedule[k.team].filter((g) => g.roof === 'outdoors').map((g) => rows.get(g.w));
  assert.ok(dome.length && out.length);
  // Weekly points still depend on the game total, so compare the whole set rather than a
  // single pair: no dome week may be a numerical clone of an outdoor week.
  for (const a of dome) {
    for (const b of out) {
      assert.notEqual(a.muPoints, b.muPoints,
        `${k.name}: dome week ${a.week} scored identically to outdoor week ${b.week}`);
    }
  }
});

/* -------------------------------------------------------- 5. real history */

test('historicalPPG reproduces arithmetic done by hand off the log rows', () => {
  const keys = PACK.logKeys;
  // Full PPR, written out longhand so this does not just re-run scoring.js.
  const byHand = (L) => 0.04 * L.pyd + 4 * L.ptd - 2 * L.pint
    + 0.1 * L.ryd + 6 * L.rtd
    + 1 * L.rec + 0.1 * L.reyd + 6 * L.retd
    - 2 * L.fuml + 6 * L.sttd
    + 2 * (L.p2p + L.r2p + L.re2p);

  let checked = 0;
  for (const pos of ['QB', 'RB', 'WR', 'TE']) {
    for (const { player } of topAt(pos, 8)) {
      if (!Array.isArray(player.log) || player.log.length === 0) continue;
      let total = 0;
      const perGame = [];
      for (const row of player.log) {
        const L = {};
        keys.forEach((k, i) => { L[k] = row[i + 3]; });
        const pts = byHand(L);
        total += pts;
        perGame.push({ season: row[0], week: row[1], opp: row[2], pts });
      }
      const h = historicalPPG(player, FULL, PACK);
      assert.equal(h.covered, true);
      assert.equal(h.games, player.log.length, `${player.name}: game count`);
      assert.ok(close(h.points, total, 1e-6), `${player.name}: total ${h.points} vs ${total}`);
      assert.ok(close(h.ppg, total / player.log.length, 1e-6),
        `${player.name}: ppg ${h.ppg} vs ${total / player.log.length}`);

      // The per-game series must line up row for row, so the UI can plot it.
      assert.equal(h.series.length, perGame.length);
      for (let i = 0; i < perGame.length; i++) {
        assert.equal(h.series[i].season, perGame[i].season);
        assert.equal(h.series[i].week, perGame[i].week);
        assert.equal(h.series[i].opp, perGame[i].opp);
        assert.ok(close(h.series[i].pts, perGame[i].pts, 1e-6));
      }
      checked++;
    }
  }
  assert.ok(checked >= 20, `expected to hand-check many players, checked ${checked}`);
});

test('historicalPPG on a hand-built fixture gives the hand-computed number', () => {
  const logKeys = ['pyd', 'ptd', 'pint', 'ryd', 'rtd', 'rec', 'reyd', 'retd', 'fuml'];
  const fixture = {
    meta: { season: 2026, regSeasonWeeks: 18, logSeasons: [2025] },
    logKeys,
    teams: { KC: { name: 'Chiefs', bye: 5 } },
    schedule: { KC: [{ w: 1, opp: 'DEN', home: true, roof: 'outdoors', implied: 24 }] },
    teamFactors: { KC: { 1: { pass: 1, rush: 1, td: 1 } } },
    dvp: { DEN: { WR: 1, QB: 1 } },
    players: [],
  };
  //                     pyd ptd pint ryd rtd rec reyd retd fuml
  const wr = {
    id: 'w1', name: 'Test WR', pos: 'WR', team: 'KC', bye: 5, avail: 1, cv: 0.4,
    mu: { rec: 5, reyd: 60, retd: 0.4 },
    log: [
      [2025, 1, 'DEN', 0, 0, 0, 10, 0, 7, 88, 1, 0],
      [2025, 2, 'LV', 0, 0, 0, 0, 0, 3, 25, 0, 1],
    ],
  };
  fixture.players.push(wr);

  // Game 1: 0.1*10 + 7*1 + 0.1*88 + 6*1            = 1 + 7 + 8.8 + 6   = 22.8
  // Game 2:            3*1 + 0.1*25       + (-2)*1 =     3 + 2.5 - 2   =  3.5
  const h = historicalPPG(wr, FULL, fixture);
  assert.equal(h.games, 2);
  assert.equal(h.points, 26.3);
  assert.equal(h.ppg, 13.15);
  assert.equal(h.best, 22.8);
  assert.equal(h.worst, 3.5);
  assert.deepEqual(h.seasons, [2025]);
  assert.deepEqual(h.bySeason, [{ season: 2025, games: 2, points: 26.3, ppg: 13.15 }]);
  assert.equal(h.series[0].opp, 'DEN');
  assert.equal(h.series[1].pts, 3.5);

  // Half PPR removes exactly 0.5 per reception: 10 receptions over 2 games = -2.5 ppg.
  const half = historicalPPG(wr, HALF, fixture);
  assert.equal(half.points, 26.3 - 0.5 * 10);
  assert.equal(half.ppg, 13.15 - 2.5);

  // A QB line, to exercise the passing half of the vocabulary.
  const qb = {
    id: 'q1', name: 'Test QB', pos: 'QB', team: 'KC', bye: 5, avail: 1, cv: 0.3,
    mu: { patt: 35, pyd: 260, ptd: 1.8 },
    log: [[2025, 1, 'DEN', 300, 3, 1, 40, 1, 0, 0, 0, 0]],
  };
  // 0.04*300 + 4*3 - 2*1 + 0.1*40 + 6*1 = 12 + 12 - 2 + 4 + 6 = 32
  assert.equal(historicalPPG(qb, FULL, fixture).ppg, 32);
});

test('history re-scores with the config, exactly like the projection does', () => {
  for (const { player } of topAt('WR', 10)) {
    if (!Array.isArray(player.log) || player.log.length === 0) continue;
    const full = historicalPPG(player, FULL, PACK);
    const half = historicalPPG(player, HALF, PACK);
    const recIdx = PACK.logKeys.indexOf('rec');
    let recs = 0;
    for (const row of player.log) recs += row[recIdx + 3];
    assert.ok(close(full.points - half.points, 0.5 * recs, 1e-6),
      `${player.name}: history must re-derive from the same components`);
  }
});

test('history is honest about what the pack cannot tell it', () => {
  const k = (VIEW.byPos.get('K') || []).find((p) => Array.isArray(p.log) && p.log.length > 0);
  if (k) {
    const h = historicalPPG(k, FULL, PACK);
    assert.equal(h.covered, false, 'a kicker has no kicking components in logKeys');
    assert.equal(h.ppg, null, 'so no PPG may be reported, least of all zero');
    assert.equal(h.games, 0);
    assert.deepEqual(h.series, []);
    assert.ok(/not recoverable/i.test(h.note));
  }

  const d = (VIEW.byPos.get('DST') || [])[0];
  const hd = historicalPPG(d, FULL, PACK);
  assert.equal(hd.covered, false);
  assert.equal(hd.ppg, null);
  assert.ok(hd.note.length > 0);

  // A player with no logged games: covered, but nothing to average.
  const rookie = { id: 'r', name: 'Rookie', pos: 'WR', team: 'KC', bye: 5, mu: { rec: 3 } };
  const hr = historicalPPG(rookie, FULL, PACK);
  assert.equal(hr.covered, true);
  assert.equal(hr.games, 0);
  assert.equal(hr.ppg, null);
  assert.ok(hr.note.length > 0);

  assert.equal(historicalPPG(null, FULL, PACK).ppg, null);
});

test('unpackLog reverses the packed row order', () => {
  const wr = topAt('WR', 1)[0].player;
  const rows = unpackLog(wr, PACK);
  assert.equal(rows.length, wr.log.length);
  for (let i = 0; i < rows.length; i++) {
    assert.equal(rows[i].season, wr.log[i][0]);
    assert.equal(rows[i].week, wr.log[i][1]);
    assert.equal(rows[i].opp, wr.log[i][2]);
    PACK.logKeys.forEach((k, j) => assert.equal(rows[i].line[k], wr.log[i][j + 3]));
    // And scoring it reproduces the reported series.
    const pts = scoreLine(rows[i].line, FULL, wr.pos);
    assert.ok(close(pts, historicalPPG(wr, FULL, PACK).series[i].pts, 1e-6));
  }
  assert.deepEqual(unpackLog({ pos: 'WR' }, PACK), []);
});

/* ------------------------------------------------------------ 6. performance */

test('projectFast re-derives the whole board in well under 50ms', () => {
  const players = VIEW.players;
  assert.ok(players.length >= 1000, `expected ~1000 players, got ${players.length}`);

  // Each pass uses a DIFFERENT scoring config, which is exactly what happens when the user
  // drags the PPR slider: nothing may be cached across the change.
  function pass(i) {
    const cfg = cloneScoring(FULL);
    cfg.rec.rec = 0.5 + i * 0.01;
    let acc = 0;
    for (let j = 0; j < players.length; j++) {
      acc += projectFast(players[j], { pack: VIEW, cfg }).mean;
    }
    return acc;
  }

  for (let i = 0; i < 6; i++) pass(i); // warm up the JIT

  const times = [];
  for (let i = 0; i < 9; i++) {
    const t0 = process.hrtime.bigint();
    const acc = pass(i);
    const t1 = process.hrtime.bigint();
    assert.ok(Number.isFinite(acc) && acc > 0);
    times.push(Number(t1 - t0) / 1e6);
  }
  times.sort((a, b) => a - b);
  const median = times[4];
  const best = times[0];

  assert.ok(median < 50,
    `projectFast over ${players.length} players took ${median.toFixed(1)}ms (median of 9); `
    + 'the board must re-derive faster than that to stay live under a slider');
  assert.ok(best < 40,
    `best-case pass was ${best.toFixed(1)}ms, which leaves no headroom under 50ms`);
});

test('projectFast produces a finite, ordered projection for every player in the pack', () => {
  let projected = 0;
  let empty = 0;
  for (const p of VIEW.players) {
    const r = projectFast(p, { pack: VIEW, cfg: FULL });
    for (const k of ['mean', 'sd', 'p10', 'p50', 'p90']) {
      assert.ok(Number.isFinite(r[k]), `${p.name}: ${k} is ${r[k]}`);
    }
    assert.ok(r.sd >= 0, `${p.name}: negative sd`);
    assert.ok(r.p10 <= r.p50 + EPS && r.p50 <= r.p90 + EPS,
      `${p.name}: quantiles out of order (${r.p10}, ${r.p50}, ${r.p90})`);
    assert.equal(r.games + r.byes.length, r.weeks.length);
    assert.equal(r.perWeek.length, r.weeks.length);
    for (const row of r.perWeek) {
      assert.ok(Number.isFinite(row.mean) && Number.isFinite(row.sd));
      assert.ok(row.p10 <= row.p50 + EPS && row.p50 <= row.p90 + EPS);
    }
    if (r.games > 0) projected++;
    else {
      empty++;
      assert.ok(r.note.length > 0, `${p.name} projects nothing but explains nothing`);
      assert.equal(r.mean, 0);
    }
  }
  assert.ok(projected > 950, `expected nearly every player to project, got ${projected}`);
  assert.ok(empty < 20, `too many unprojectable players (${empty}) — check the pack`);
});

/* ---------------------------------------------- projection shape and behavior */

test('a season total is the sum of its weeks', () => {
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K', 'DST']) {
    for (const { player } of topAt(pos, 4)) {
      const s = seasonTotal(player, { pack: VIEW, cfg: FULL });
      const sum = s.perWeek.reduce((acc, r) => acc + r.mean, 0);
      assert.ok(close(s.mean, sum, 1e-4),
        `${player.name}: total ${s.mean} != sum of weeks ${sum}`);
      // Each week's mean is the availability-weighted line score.
      for (const row of s.perWeek) {
        if (row.bye) continue;
        assert.ok(close(row.mean, row.muPoints * row.playProb, 1e-4));
      }
    }
  }
});

test('offensive weekly means equal scoreLine of weeklyMu, availability aside', () => {
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K']) {
    for (const { player } of topAt(pos, 4)) {
      const s = seasonTotal(player, { pack: VIEW, cfg: FULL });
      for (const row of s.perWeek) {
        if (row.bye) continue;
        const mu = weeklyMu(player, row.week, PACK);
        assert.ok(close(row.muPoints, scoreLine(mu, FULL, player.pos), 1e-6),
          `${player.name} week ${row.week}: ${row.muPoints} vs ${scoreLine(mu, FULL, player.pos)}`);
      }
    }
  }
});

test('a D/ST mean integrates the tier stacks instead of evaluating them at the mean', () => {
  // tierPoints(E[x]) != E[tierPoints(x)]. In this league both stacks are live, so evaluating
  // at the mean is a real error. Assert the two genuinely differ for most defenses.
  let differ = 0;
  let total = 0;
  for (const d of VIEW.byPos.get('DST') || []) {
    const s = seasonTotal(d, { pack: VIEW, cfg: FULL });
    let naive = 0;
    for (const row of s.perWeek) {
      if (row.bye) continue;
      naive += scoreLine(weeklyMu(d, row.week, PACK), FULL, 'DST');
      total++;
    }
    if (Math.abs(s.mean - naive) > 1) differ++;
    assert.ok(s.sd > 0, `${d.name}: a defense with no variance is not a projection`);
  }
  assert.ok(total > 300);
  assert.ok(differ > 20,
    `expected the tier integration to move most defenses, moved ${differ}`);
});

test('restOfSeason projects only what remains', () => {
  const wr = topAt('WR', 1)[0].player;
  const all = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  const from14 = restOfSeason(wr, { pack: VIEW, cfg: FULL, fromWeek: 14 });

  assert.equal(from14.fromWeek, 14);
  assert.deepEqual(from14.weeks, [14, 15, 16, 17, 18].filter((w) => w <= VIEW.lastWeek));
  assert.ok(from14.mean < all.mean);
  const tail = all.perWeek.filter((r) => r.week >= 14).reduce((a, r) => a + r.mean, 0);
  assert.ok(close(from14.mean, tail, 1e-4));

  // Preseason pack: rest of season is the whole season.
  const ros = restOfSeason(wr, { pack: VIEW, cfg: FULL });
  assert.equal(ros.fromWeek, 1);
  assert.equal(ros.mean, all.mean);

  // Past the end of the season there is nothing left, and it says so.
  const done = restOfSeason(wr, { pack: VIEW, cfg: FULL, fromWeek: VIEW.lastWeek + 5 });
  assert.equal(done.games, 0);
  assert.equal(done.mean, 0);
  assert.ok(done.note.length > 0);
});

test('a single week keeps its point mass at zero when the player might not play', () => {
  const risky = VIEW.players.find((p) => p.pos === 'WR' && p.avail < 0.9 && p.mu && p.mu.rec > 3);
  assert.ok(risky, 'expected at least one injury-prone starter in the pack');
  const w = scheduledWeeks(risky.team)[0];
  const one = weeklyProjection(risky, w, { pack: VIEW, cfg: FULL });

  assert.equal(one.games, 1);
  assert.equal(one.dist.kind, 'mixture');
  assert.ok(one.p10 >= 0);
  if (risky.avail < 0.9) assert.equal(one.p10, 0, 'a 10%+ chance of missing IS a floor of zero');
  assert.ok(one.p90 > one.mean, 'the ceiling must sit above the mean');

  // A player who always plays has a floor above zero.
  const safe = { id: 's', name: 'Iron Man', pos: 'WR', team: risky.team, bye: risky.bye,
    avail: 1, cv: 0.3, mu: { rec: 6, reyd: 80, retd: 0.5, tgt: 9 } };
  const sOne = weeklyProjection(safe, w, { pack: VIEW, cfg: FULL });
  assert.ok(sOne.p10 > 0);
  assert.ok(sOne.p10 < sOne.p50 && sOne.p50 < sOne.p90);
});

test('availability scales the mean and widens the band', () => {
  const wr = topAt('WR', 1)[0].player;
  const always = projectFast(wr, { pack: VIEW, cfg: FULL, playProb: 1, perWeek: false });
  const risky = projectFast(wr, { pack: VIEW, cfg: FULL, playProb: 0.6, perWeek: false });
  assert.ok(close(risky.mean, always.mean * 0.6, 1e-4));
  assert.ok(risky.sd / risky.mean > always.sd / always.mean,
    'a shakier player must carry a wider relative band');

  const never = projectFast(wr, { pack: VIEW, cfg: FULL, playProb: 0, perWeek: false });
  assert.equal(never.mean, 0);
});

test('meanUncertainty is opt-out and labeled as inferred', () => {
  const wr = topAt('WR', 1)[0].player;
  const withU = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  const noU = seasonTotal(wr, { pack: VIEW, cfg: FULL, meanUncertainty: 0 });

  assert.equal(withU.mean, noU.mean, 'it must widen the band, never move the mean');
  assert.ok(withU.sd > noU.sd);
  assert.ok(withU.inferred.some((s) => /meanUncertainty/.test(s)),
    'contract section 10: an inferred assumption must be labeled');
  assert.ok(!noU.inferred.some((s) => /meanUncertainty/.test(s)));

  // A single week never gets it: there is no season-long drift inside one game.
  const one = weeklyProjection(wr, scheduledWeeks(wr.team)[0], { pack: VIEW, cfg: FULL });
  assert.ok(!one.inferred.some((s) => /meanUncertainty/.test(s)));
});

test('quantileOf agrees with the reported quantiles', () => {
  for (const pos of ['WR', 'QB', 'K', 'DST']) {
    const p = topAt(pos, 1)[0].player;
    const s = seasonTotal(p, { pack: VIEW, cfg: FULL });
    assert.ok(close(quantileOf(s, 0.1), s.p10, 1e-3));
    assert.ok(close(quantileOf(s, 0.5), s.p50, 1e-3));
    assert.ok(close(quantileOf(s, 0.9), s.p90, 1e-3));
    assert.ok(quantileOf(s, 0.25) > s.p10 && quantileOf(s, 0.25) < s.p50);

    const one = weeklyProjection(p, scheduledWeeks(p.team)[0], { pack: VIEW, cfg: FULL });
    assert.ok(close(quantileOf(one, 0.1), one.p10, 1e-6));
    assert.ok(close(quantileOf(one, 0.9), one.p90, 1e-6));
  }
  assert.equal(quantileOf(null, 0.5), 0);
});

test('a week range can be given as an array, a number or a from/to pair', () => {
  const wr = topAt('WR', 1)[0].player;
  const weeks = scheduledWeeks(wr.team).slice(0, 3);
  const byArray = projectFast(wr, { pack: VIEW, cfg: FULL, weeks });
  const byRange = projectFast(wr, {
    pack: VIEW, cfg: FULL, weeks: { from: weeks[0], to: weeks[weeks.length - 1] },
  });
  assert.ok(byRange.mean >= byArray.mean - 1e-9);
  const one = projectFast(wr, { pack: VIEW, cfg: FULL, weeks: weeks[0] });
  assert.equal(one.games, 1);
  // Out-of-order and duplicate weeks normalize.
  const messy = projectFast(wr, { pack: VIEW, cfg: FULL, weeks: [weeks[2], weeks[0], weeks[0], weeks[1]] });
  assert.deepEqual(messy.weeks, weeks.slice().sort((a, b) => a - b));
  assert.ok(close(messy.mean, byArray.mean, 1e-9));
});

test('perWeek can be switched off without changing the answer', () => {
  const wr = topAt('WR', 1)[0].player;
  const withRows = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  const without = projectFast(wr, {
    pack: VIEW, cfg: FULL, weeks: { from: VIEW.firstWeek, to: VIEW.lastWeek }, perWeek: false,
  });
  assert.equal(without.perWeek, null);
  for (const k of ['mean', 'sd', 'p10', 'p50', 'p90', 'games']) {
    assert.equal(without[k], withRows[k], `${k} changed when perWeek was switched off`);
  }
});

test('the raw pack and a loaded view are interchangeable', () => {
  const wr = topAt('WR', 1)[0].player;
  const a = seasonTotal(wr, { pack: PACK, cfg: FULL });
  const b = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  assert.equal(a.mean, b.mean);
  assert.equal(a.sd, b.sd);
});

/* ------------------------------------------------------- missing data honesty */

test('missing data is reported, never invented', () => {
  const noTeam = { id: 'a', name: 'Free Agent', pos: 'WR', team: 'FA', bye: 0, avail: 1, cv: 0.4, mu: { rec: 5 } };
  const r1 = projectFast(noTeam, { pack: VIEW, cfg: FULL });
  assert.equal(r1.mean, 0);
  assert.equal(r1.games, 0);
  assert.ok(/schedule/i.test(r1.note));

  const noMu = { id: 'b', name: 'No Projection', pos: 'WR', team: 'KC', bye: 5, avail: 1, cv: 0.4 };
  const r2 = projectFast(noMu, { pack: VIEW, cfg: FULL });
  assert.equal(r2.mean, 0);
  assert.ok(/manual/i.test(r2.note), 'the app must offer manual entry, not a fabricated zero');

  const noKicking = { id: 'c', name: 'No Kicker Data', pos: 'K', team: 'KC', bye: 5, avail: 1, cv: 0.4 };
  assert.ok(projectFast(noKicking, { pack: VIEW, cfg: FULL }).note.length > 0);

  const noDst = { id: 'd', name: 'No DST Data', pos: 'DST', team: 'KC', bye: 5, avail: 1, cv: 0.5 };
  assert.ok(projectFast(noDst, { pack: VIEW, cfg: FULL }).note.length > 0);

  for (const bad of [null, undefined, 42, 'x']) {
    const r = projectFast(bad, { pack: VIEW, cfg: FULL });
    assert.equal(r.mean, 0);
    assert.ok(r.note.length > 0);
  }
  // No pack at all: nothing throws, nothing is invented.
  const r3 = projectFast(topAt('WR', 1)[0].player, { cfg: FULL });
  assert.equal(r3.mean, 0);
});

/* --------------------------------------------------------------- purity */

test('nothing in the pack is ever mutated', () => {
  const before = JSON.stringify(PACK);
  for (const p of VIEW.players) {
    projectFast(p, { pack: VIEW, cfg: FULL });
    weeklyMu(p, 1, VIEW);
    historicalPPG(p, HALF, VIEW);
  }
  seasonTotal(VIEW.players[0], { pack: PACK, cfg: HALF });
  restOfSeason(VIEW.players[1], { pack: PACK, cfg: FULL, fromWeek: 9 });
  assert.equal(JSON.stringify(PACK), before, 'the pack changed under a projection pass');
});

test('projections do not alias each other or the pack', () => {
  const wr = topAt('WR', 1)[0].player;
  const a = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  const b = seasonTotal(wr, { pack: VIEW, cfg: FULL });
  assert.notEqual(a, b);
  assert.notEqual(a.perWeek, b.perWeek);
  assert.equal(a.mean, b.mean);
  a.perWeek[0].mean = -1;
  assert.notEqual(b.perWeek[0].mean, -1);
  assert.equal(seasonTotal(wr, { pack: VIEW, cfg: FULL }).mean, b.mean);
});

test('results are deterministic and independent of the order players are projected in', () => {
  const sample = VIEW.players.slice(0, 200);
  const forward = sample.map((p) => projectFast(p, { pack: VIEW, cfg: FULL, perWeek: false }).mean);
  const backward = sample.slice().reverse()
    .map((p) => projectFast(p, { pack: VIEW, cfg: FULL, perWeek: false }).mean)
    .reverse();
  assert.deepEqual(backward, forward);
});

/* ------------------------------------------------------------ the sim engine */

test('project equals projectFast when no simulation engine is wired in', () => {
  assert.equal(simEngine(), null);
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K', 'DST']) {
    for (const { player } of topAt(pos, 3)) {
      const a = project(player, { pack: VIEW, cfg: FULL });
      const b = projectFast(player, { pack: VIEW, cfg: FULL });
      assert.equal(a.method, 'closed-form');
      assert.deepEqual(
        { m: a.mean, s: a.sd, l: a.p10, x: a.p90 },
        { m: b.mean, s: b.sd, l: b.p10, x: b.p90 },
      );
    }
  }
});

test('a wired-in sim engine takes over, and its input carries what it needs', () => {
  const wr = topAt('WR', 1)[0].player;
  let seen = null;
  const engine = {
    simSeason(spec) {
      seen = spec;
      return { mean: 300, sd: 50 };
    },
  };

  const r = project(wr, { pack: VIEW, cfg: FULL, sim: engine, iters: 777, seed: 42 });
  assert.equal(r.method, 'sim');
  assert.equal(r.mean, 300);
  assert.equal(r.sd, 50);
  assert.ok(r.p10 < 300 && r.p90 > 300);
  assert.ok(r.closedForm && Number.isFinite(r.closedForm.mean),
    'the closed form must stay visible next to the simulated answer');

  assert.equal(seen.player, wr);
  assert.equal(seen.cfg, FULL);
  assert.equal(seen.pack, PACK);
  assert.equal(seen.view, VIEW);
  assert.equal(seen.iters, 777);
  assert.equal(seen.seed, 42);
  assert.ok(Array.isArray(seen.weeks) && seen.weeks.length > 0);
  assert.deepEqual(seen.weeklyMu(wr, seen.weeks[0]), weeklyMu(wr, seen.weeks[0], PACK));
});

test('a sim engine returning samples is summarized correctly', () => {
  const wr = topAt('WR', 1)[0].player;
  const samples = [];
  for (let i = 0; i < 1001; i++) samples.push(100 + i * 0.2); // 100 .. 300, uniform
  const r = project(wr, { pack: VIEW, cfg: FULL, sim: () => samples });
  assert.equal(r.method, 'sim');
  assert.ok(close(r.mean, 200, 1e-6));
  assert.ok(close(r.p50, 200, 1e-6));
  assert.ok(close(r.p10, 120, 1e-6));
  assert.ok(close(r.p90, 280, 1e-6));
  assert.ok(r.sd > 0);
});

test('an untrustworthy sim engine is refused, and the refusal is reported', () => {
  const wr = topAt('WR', 1)[0].player;
  const good = projectFast(wr, { pack: VIEW, cfg: FULL });

  const cases = [
    ['throws', () => { throw new Error('boom'); }],
    ['returns nothing', () => undefined],
    ['returns junk', () => ({ hello: 'world' })],
    ['returns NaN', () => ({ mean: NaN, sd: NaN })],
    ['returns too few samples', () => [1]],
  ];
  for (const [label, sim] of cases) {
    const r = project(wr, { pack: VIEW, cfg: FULL, sim });
    assert.equal(r.method, 'closed-form', `${label}: should have fallen back`);
    assert.equal(r.mean, good.mean, `${label}: fallback must be the closed form`);
    assert.ok(r.note.length > 0, `${label}: the fallback must be explained`);
  }
});

test('an engine exposing simPlayerWeek is driven week by week and summed', () => {
  const wr = topAt('WR', 1)[0].player;
  const calls = [];
  const N = 500;
  const engine = {
    makeRng(seed) { const r = () => 0.5; r.seed = seed; return r; },
    simPlayerWeek(player, week, cfg, pack, rng, iters) {
      calls.push({ player, week, cfg, pack, rng, iters });
      const samples = new Float64Array(N);
      // Week w contributes exactly w points in every draw, so the total is predictable.
      for (let i = 0; i < N; i++) samples[i] = week;
      return { mean: week, sd: 0, samples };
    },
  };

  const weeks = scheduledWeeks(wr.team).slice(0, 4);
  const r = project(wr, { pack: VIEW, cfg: FULL, sim: engine, weeks, iters: 321, seed: 7 });

  assert.equal(r.method, 'sim');
  assert.equal(calls.length, weeks.length, 'every requested week must be drawn');
  assert.deepEqual(calls.map((c) => c.week), weeks);
  assert.equal(calls[0].player, wr);
  assert.equal(calls[0].cfg, FULL);
  assert.equal(calls[0].pack, PACK);
  assert.equal(calls[0].iters, 321);
  assert.equal(calls[0].rng.seed, 7, 'the engine RNG must be seeded from opts.seed');
  assert.ok(calls.every((c) => c.rng === calls[0].rng), 'one RNG stream across the weeks');

  const expected = weeks.reduce((a, w) => a + w, 0);
  assert.ok(close(r.mean, expected, 1e-6), `${r.mean} != ${expected}`);
  assert.equal(r.sd, 0);
  assert.ok(Number.isFinite(r.closedForm.mean));

  // simMode 'season' skips the per-week path entirely.
  calls.length = 0;
  const seasonEngine = { ...engine, simSeason: () => ({ mean: 9, sd: 1 }) };
  const r2 = project(wr, { pack: VIEW, cfg: FULL, sim: seasonEngine, weeks, simMode: 'season' });
  assert.equal(r2.mean, 9);
  assert.equal(calls.length, 0);
});

test('a per-week engine that misbehaves is refused too', () => {
  const wr = topAt('WR', 1)[0].player;
  const good = projectFast(wr, { pack: VIEW, cfg: FULL });
  const weeks = scheduledWeeks(wr.team).slice(0, 3);

  const cases = [
    ['no samples', { simPlayerWeek: () => ({ mean: 10, sd: 2 }) }],
    ['ragged samples', {
      simPlayerWeek: (p, w) => ({ samples: new Float64Array(w === weeks[0] ? 10 : 11) }),
    }],
    ['NaN samples', { simPlayerWeek: () => ({ samples: [NaN, NaN, NaN] }) }],
    ['throws', { simPlayerWeek: () => { throw new Error('nope'); } }],
    ['returns nothing', { simPlayerWeek: () => null }],
  ];
  for (const [label, sim] of cases) {
    const r = project(wr, { pack: VIEW, cfg: FULL, sim, weeks });
    assert.equal(r.method, 'closed-form', `${label}: should have fallen back`);
    assert.ok(r.note.length > 0, `${label}: the fallback must be explained`);
    assert.ok(Number.isFinite(r.mean));
  }
  assert.ok(good.mean > 0);
});

test('the real sim.js, when present, plugs straight in', async () => {
  let sim = null;
  try {
    sim = await import('../app/js/sim.js');
  } catch {
    return; // sim.js is not built yet; project() is the closed form and that is contractual.
  }
  if (!sim || typeof sim.simPlayerWeek !== 'function') return;

  const wr = topAt('WR', 1)[0].player;
  const weeks = scheduledWeeks(wr.team).slice(0, 5);
  const closed = projectFast(wr, { pack: VIEW, cfg: FULL, weeks });
  const r = project(wr, { pack: VIEW, cfg: FULL, sim, weeks, iters: 600, seed: 11 });

  // Either it was adopted, or it was refused and said so. Both are correct outcomes; what is
  // NOT allowed is a silently wrong number.
  assert.ok(Number.isFinite(r.mean));
  assert.ok(r.p10 <= r.p50 + EPS && r.p50 <= r.p90 + EPS);
  if (r.method === 'sim') {
    assert.ok(r.mean > 0, 'a simulated elite WR should score');
    // The closed form and the simulation are two roads to the same mean. They will not agree
    // exactly (thresholds and skew differ), but a large gap means one of them is wrong.
    const rel = Math.abs(r.mean - closed.mean) / closed.mean;
    assert.ok(rel < 0.3,
      `sim (${r.mean}) and closed form (${closed.mean}) disagree by ${(rel * 100).toFixed(0)}%`);
    assert.ok(r.sd > 0);
    // Reproducible: the same seed must give the same answer.
    const again = project(wr, { pack: VIEW, cfg: FULL, sim, weeks, iters: 600, seed: 11 });
    assert.equal(again.mean, r.mean);
    assert.equal(again.p90, r.p90);
  } else {
    assert.equal(r.method, 'closed-form');
    assert.ok(r.note.length > 0);
  }
});

test('the closed form agrees with the Monte Carlo it stands in for', async () => {
  let sim = null;
  try {
    sim = await import('../app/js/sim.js');
  } catch {
    return;
  }
  if (!sim || typeof sim.simPlayerWeek !== 'function') return;

  // The whole point of a closed form is that it is the same answer, cheaply. Compare the
  // full-season mean and (with the season-level role-risk term switched off, which the sim
  // does not model) the spread, across the board and down the depth chart.
  const picks = [];
  for (const pos of ['QB', 'RB', 'WR', 'TE', 'K', 'DST']) {
    const ranked = topAt(pos, 21).map((x) => x.player);
    for (const i of [0, 8, 20]) if (ranked[i]) picks.push(ranked[i]);
  }

  let compared = 0;
  for (const p of picks) {
    if (!PACK.schedule[p.team]) continue;
    const weeks = scheduledWeeks(p.team);
    const closed = projectFast(p, { pack: VIEW, cfg: FULL, weeks, perWeek: false, meanUncertainty: 0 });
    const s = project(p, { pack: VIEW, cfg: FULL, weeks, sim, iters: 4000, seed: 3 });
    if (s.method !== 'sim' || !(closed.mean > 0)) continue;
    compared++;

    const relMean = Math.abs(s.mean - closed.mean) / closed.mean;
    assert.ok(relMean < 0.05,
      `${p.name}: closed form ${closed.mean} vs simulation ${s.mean} (${(relMean * 100).toFixed(1)}%)`);

    const ratio = closed.sd / s.sd;
    assert.ok(ratio > 0.6 && ratio < 1.5,
      `${p.name}: closed-form sd ${closed.sd} vs simulated ${s.sd} (ratio ${ratio.toFixed(2)})`);
  }
  assert.ok(compared >= 12, `expected to compare many players, compared ${compared}`);
});

test('useSim registers and unregisters a default engine', () => {
  const wr = topAt('WR', 1)[0].player;
  try {
    useSim({ simSeason: () => ({ mean: 111, sd: 11 }) });
    assert.ok(simEngine());
    assert.equal(project(wr, { pack: VIEW, cfg: FULL }).mean, 111);
    // An explicit `sim: false` opts one call back out.
    assert.equal(project(wr, { pack: VIEW, cfg: FULL, sim: false }).method, 'closed-form');
  } finally {
    useSim(null);
  }
  assert.equal(simEngine(), null);
  assert.equal(project(wr, { pack: VIEW, cfg: FULL }).method, 'closed-form');
});

/* ------------------------------------------------- the model says sane things */

test('the projected board looks like a football season, not a random number generator', () => {
  const wr1 = topAt('WR', 1)[0];
  const rb1 = topAt('RB', 1)[0];
  const qb1 = topAt('QB', 1)[0];
  const te1 = topAt('TE', 1)[0];
  const k1 = topAt('K', 1)[0];
  const d1 = topAt('DST', 1)[0];

  // Full PPR, 17-game seasons: an elite skill player lands in the 250-420 range.
  for (const top of [wr1, rb1, qb1]) {
    assert.ok(top.proj.mean > 200 && top.proj.mean < 450,
      `${top.player.name} projects ${top.proj.mean}, which is not a real season`);
  }
  assert.ok(te1.proj.mean > 100 && te1.proj.mean < 350);
  // Kickers and defenses live in a much narrower band.
  assert.ok(k1.proj.mean > 80 && k1.proj.mean < 220, `K1 ${k1.proj.mean}`);
  assert.ok(d1.proj.mean > 60 && d1.proj.mean < 220, `DST1 ${d1.proj.mean}`);

  // 4-point passing TDs compress quarterbacks: QB1 to QB12 is a smaller gap, relatively,
  // than WR1 to WR12. That is contract section 9, and the app is supposed to price it.
  const qbs = topAt('QB', 12).map((x) => x.proj.mean);
  const wrs = topAt('WR', 12).map((x) => x.proj.mean);
  const qbGap = (qbs[0] - qbs[11]) / qbs[0];
  const wrGap = (wrs[0] - wrs[11]) / wrs[0];
  assert.ok(qbGap < wrGap,
    `QB compression: QB1->QB12 drop ${qbGap} should be flatter than WR1->WR12 ${wrGap}`);
});

test('a season band is wide enough to be honest and tight enough to be useful', () => {
  for (const pos of ['QB', 'RB', 'WR', 'TE']) {
    for (const { player, proj } of topAt(pos, 6)) {
      const rel = proj.sd / proj.mean;
      assert.ok(rel > 0.08 && rel < 0.8,
        `${player.name}: season band is ${(rel * 100).toFixed(0)}% of the mean`);
      assert.ok(proj.p10 > 0, `${player.name}: an elite player's floor should not be zero`);
      assert.ok(proj.p90 > proj.mean);
    }
  }
});

test('touchdown dependence shows up as volatility, receptions as stability', () => {
  // Two synthetic receivers, same team, same week, same usage CV. One earns his points on
  // reception volume, the other on touchdowns. Full PPR is supposed to make that difference
  // legible, so the touchdown-dependent one must carry the wider band per point of mean.
  const team = 'KC';
  const week = scheduledWeeks(team)[0];
  const base = { pos: 'WR', team, bye: VIEW.byeOf(team), avail: 1, cv: 0.35 };
  const volume = { ...base, id: 'v', name: 'Volume', mu: { tgt: 12, rec: 9, reyd: 96, retd: 0.15 } };
  const tdDep = { ...base, id: 't', name: 'Touchdowns', mu: { tgt: 5, rec: 3, reyd: 40, retd: 1.6 } };

  const a = weeklyProjection(volume, week, { pack: VIEW, cfg: FULL });
  const b = weeklyProjection(tdDep, week, { pack: VIEW, cfg: FULL });
  assert.ok(a.mean > 0 && b.mean > 0);
  assert.ok((b.sd / b.mean) > (a.sd / a.mean) * 1.3,
    'the touchdown-dependent receiver must be the volatile one: '
    + `${(b.sd / b.mean).toFixed(3)} vs ${(a.sd / a.mean).toFixed(3)}`);

  // And in standard scoring the volume receiver loses far more of his value than the
  // touchdown one does. That is the reception share of value, contract section 9.
  const std = PRESETS.standard;
  const aStd = weeklyProjection(volume, week, { pack: VIEW, cfg: std });
  const bStd = weeklyProjection(tdDep, week, { pack: VIEW, cfg: std });
  assert.ok((a.mean - aStd.mean) / a.mean > (b.mean - bStd.mean) / b.mean * 1.5,
    'the volume receiver is the one full PPR is paying for');
});
